module.exports = {
	EMAIL_ALREADY_EXISTS : "EL_001",
	SCHOOLCODE_ALREADY_EXISTS : "EL_002",
	NOT_REGISTERED : "EL_003",
	INVALID_EMAIL_PASSWORD : "EL_004",
	SUCCESS : "EL_200",
	DB_ERROR : "EL_005",
	NO_SCHOOLS : "EL_006",
	SUBJECT_EXIST : "EL_007",
	SUBJECT_NOT_EXIST : "EL_008",
	CHAPTER_EXIST : "EL_009",
	CHAPTER_NOT_EXIST : "EL_010",
};
